Repository dedis/dela, pull requests merged in 2020-04, with the labels that each got.

#28 Creates new stream connection when an address is in the "neighbours" list
  mino/minogrpc/mod.go
  mino/minogrpc/mod_test.go
  mino/minogrpc/overlay.go
  mino/minogrpc/overlay_test.go
  mino/minogrpc/server.go
  mino/minogrpc/server_test.go
  mino/minogrpc/traffic.go
Labels: Mino, R4M 🚀, enhancement

#32 Doc terminologies
  docs/introduction.md
Labels: R4M 🚀, documentation

#31 Consumer: smart contract consumer
  blockchain/mod.go
  blockchain/skipchain/block.go
  blockchain/skipchain/block_test.go
  encoding/mod.go
  encoding/mod_test.go
  ledger/byzcoin/messages.pb.go
  ledger/byzcoin/messages.proto
  ledger/byzcoin/mod.go
  ledger/byzcoin/mod_test.go
  ledger/byzcoin/transaction.go
  ledger/byzcoin/transaction_test.go
  ledger/byzcoin/txbag.go
  ledger/byzcoin/txbag_test.go
  ledger/byzcoin/txproc.go
  ledger/byzcoin/txproc_test.go
  ledger/byzcoin/txres.go
  ledger/byzcoin/txres_test.go
  ledger/consumer/mod.go
  ledger/consumer/smartcontract/messages.pb.go
  ledger/consumer/smartcontract/messages.proto
  ledger/consumer/smartcontract/mod.go
  ledger/consumer/smartcontract/mod_test.go
  ledger/consumer/smartcontract/tx.go
  ledger/consumer/smartcontract/tx_test.go
  ledger/inventory/mem/mod.go
  ledger/inventory/mem/mod_test.go
  ledger/inventory/mod.go
  ledger/mod.go
Labels: Byzcoin, R4M 🚀

#33 Encoding improvement
  .travis.yml
  Makefile
  blockchain/skipchain/block.go
  blockchain/skipchain/block_test.go
  blockchain/skipchain/conode.go
  blockchain/skipchain/conode_test.go
  blockchain/skipchain/handler_test.go
  blockchain/skipchain/mod.go
  blockchain/skipchain/mod_test.go
  blockchain/skipchain/validator.go
  blockchain/skipchain/validator_test.go
  consensus/cosipbft/forward_link.go
  consensus/cosipbft/forward_link_test.go
  consensus/cosipbft/mod.go
  consensus/cosipbft/mod_test.go
  consensus/cosipbft/queue.go
  consensus/cosipbft/queue_test.go
  consensus/cosipbft/requests.go
  consensus/qsc/broadcast.go
  consensus/qsc/broadcast_test.go
  consensus/qsc/history.go
  consensus/qsc/history_test.go
  consensus/qsc/mod.go
  consensus/qsc/mod_test.go
  cosi/flatcosi/handler.go
  cosi/flatcosi/handler_test.go
  cosi/flatcosi/mod.go
  cosi/flatcosi/mod_test.go
  crypto/bls/mod.go
  crypto/bls/mod_test.go
  encoding/errors.go
  encoding/errors_test.go
  encoding/mod.go
  encoding/mod_test.go
  go.mod
  go.sum
  ledger/byzcoin/mod.go
  ledger/byzcoin/txproc.go
  ledger/byzcoin/txproc_test.go
  ledger/consumer/smartcontract/mod.go
  ledger/consumer/smartcontract/tx.go
  ledger/consumer/smartcontract/tx_test.go
  ledger/inventory/mem/mod_test.go
  mino/gossip/flat.go
  mino/minoch/rpc_test.go
  mino/minogrpc/mod.go
  mino/minogrpc/mod_test.go
  mino/minogrpc/overlay.go
  mino/minogrpc/overlay_test.go
  mino/minogrpc/server.go
  mino/minogrpc/server_test.go
  mino/minogrpc/traffic.go
Labels: R4M 🚀, enhancement

#34 Ledger acess rights control
  crypto/bls/mod.go
  crypto/bls/mod_test.go
  crypto/common/mod.go
  crypto/common/mod_test.go
  crypto/mod.go
  docs/introduction.md
  encoding/mod.go
  encoding/mod_test.go
  ledger/arc/common/mod.go
  ledger/arc/common/mod_test.go
  ledger/arc/darc/contract/mod.go
  ledger/arc/darc/contract/mod_test.go
  ledger/arc/darc/expr.go
  ledger/arc/darc/expr_test.go
  ledger/arc/darc/messages.pb.go
  ledger/arc/darc/messages.proto
  ledger/arc/darc/mod.go
  ledger/arc/darc/mod_test.go
  ledger/arc/mod.go
  ledger/arc/mod_test.go
  ledger/byzcoin/mod.go
  ledger/byzcoin/mod_test.go
  ledger/byzcoin/txproc.go
  ledger/byzcoin/txproc_test.go
  ledger/consumer/mod.go
  ledger/consumer/smartcontract/context.go
  ledger/consumer/smartcontract/context_test.go
  ledger/consumer/smartcontract/messages.pb.go
  ledger/consumer/smartcontract/messages.proto
  ledger/consumer/smartcontract/mod.go
  ledger/consumer/smartcontract/mod_test.go
  ledger/consumer/smartcontract/tx.go
  ledger/consumer/smartcontract/tx_test.go
  ledger/inventory/mem/mod_test.go
Labels: Byzcoin, R4M 🚀

#35 Sets a custom check for comments length
  .travis.yml
  Makefile
  consensus/qsc/broadcast.go
  go.mod
  go.sum
  internal/mcheck/mod.go
  internal/mcheck/mod_test.go
  internal/mcheck/testdata/src/comment/mod1.go
  internal/mcheck/testdata/src/comment/mod2.go
  internal/mcheck/testdata/src/ifcheck/mod.go
  internal/mcheck/testdata/testIfCheck.go
  ledger/inventory/mem/mod.go
  mino/minoch/manager.go
  mino/minogrpc/server_test.go
Labels: R4M 🚀, enhancement

#36 Collective Signing using stream and with threshold support
  blockchain/skipchain/block_test.go
  blockchain/skipchain/conode.go
  blockchain/skipchain/conode_test.go
  blockchain/skipchain/mod.go
  blockchain/skipchain/mod_test.go
  consensus/cosipbft/mod.go
  consensus/cosipbft/mod_test.go
  cosi/flatcosi/mod.go
  cosi/flatcosi/mod_test.go
  cosi/mod.go
  cosi/threshold/actor.go
  cosi/threshold/actor_test.go
  cosi/threshold/handler.go
  cosi/threshold/handler_test.go
  cosi/threshold/messages.pb.go
  cosi/threshold/messages.proto
  cosi/threshold/mod.go
  cosi/threshold/mod_test.go
  cosi/threshold/signature.go
  cosi/threshold/signature_test.go
  crypto/bls/mod.go
  crypto/bls/mod_test.go
  crypto/mod.go
  internal/testing/fake/mod.go
  ledger/byzcoin/mod_test.go
  mino/minoch/rpc.go
  mino/mod.go
  mino/option.go
  mino/option_test.go
Labels: R4M 🚀

#37 Cleanup test
  blockchain/skipchain/block_test.go
  blockchain/skipchain/conode_test.go
  blockchain/skipchain/handler_test.go
  blockchain/skipchain/mod_test.go
  blockchain/skipchain/validator_test.go
  blockchain/viewchange/constant_test.go
  blockchain/watcher_test.go
  consensus/cosipbft/forward_link_test.go
  consensus/cosipbft/mod_test.go
  consensus/cosipbft/queue_test.go
  consensus/mod_test.go
  cosi/flatcosi/handler_test.go
  cosi/flatcosi/mod_test.go
  cosi/threshold/actor_test.go
  crypto/bls/mod_test.go
  crypto/common/mod_test.go
  internal/testing/fake/mod.go
  ledger/arc/common/mod_test.go
  ledger/arc/darc/contract/mod_test.go
  ledger/arc/darc/mod_test.go
  ledger/byzcoin/mod.go
  ledger/byzcoin/mod_test.go
  ledger/byzcoin/txproc_test.go
  ledger/consumer/smartcontract/tx_test.go
  ledger/inventory/mem/mod_test.go
Labels: R4M 🚀, enhancement

#39 Fixes missing manager when creating a new namespace
  mino/minoch/mod.go
Labels: bug
