Repository dedis/dela, pull requests merged in 2020-03, with the labels that each got.

#2 Skipchain: use a proof to verify a VerifiableBlock
  blockchain/mod.go
  blockchain/skipchain/block.go
  blockchain/skipchain/db.go
  blockchain/skipchain/handler.go
  blockchain/skipchain/messages.pb.go
  blockchain/skipchain/messages.proto
  blockchain/skipchain/mod.go
  blockchain/skipchain/mod_test.go
  blockchain/skipchain/validator.go
  go.mod
  go.sum
Labels: enhancement

#3 Skipchain unit tests
  blockchain/roster.go
  blockchain/skipchain/block.go
  blockchain/skipchain/block_test.go
  blockchain/skipchain/handler.go
  blockchain/skipchain/mod.go
  blockchain/skipchain/validator.go
  cosi/blscosi/mod.go
  crypto/bls/mod.go
  crypto/mod.go
  encoding/errors.go
  encoding/mod.go
  mod.go
Labels: enhancement

#4 Setup Travis + coverage
  .travis.yml
Labels: enhancement

#1 gRPC implementation for Mino - Handler.Process
  README.md
  go.mod
  go.sum
  mino/README.md
  mino/minoch/manager.go
  mino/minoch/mod.go
  mino/minoch/mod_test.go
  mino/minoch/rpc.go
  mino/minogrpc/mod.go
  mino/minogrpc/mod_test.go
  mino/minogrpc/overlay.go
  mino/minogrpc/overlay.pb.go
  mino/minogrpc/overlay.proto
  mino/minogrpc/server.go
  mino/minogrpc/server_test.go
  mino/mod.go
Labels: Mino

#5 Consensus module
  README.md
  blockchain/messages.pb.go
  blockchain/messages.proto
  blockchain/mod.go
  blockchain/roster.go
  blockchain/skipchain/block.go
  blockchain/skipchain/block_test.go
  blockchain/skipchain/db.go
  blockchain/skipchain/handler.go
  blockchain/skipchain/member.go
  blockchain/skipchain/messages.pb.go
  blockchain/skipchain/messages.proto
  blockchain/skipchain/mod.go
  blockchain/skipchain/mod_test.go
  blockchain/skipchain/validator.go
  consensus/cosipbft/forward_link.go
  consensus/cosipbft/forward_link_test.go
  consensus/cosipbft/messages.pb.go
  consensus/cosipbft/messages.proto
  consensus/cosipbft/mod.go
  consensus/cosipbft/mod_test.go
  consensus/cosipbft/queue.go
  consensus/cosipbft/queue_test.go
  consensus/cosipbft/storage.go
  consensus/cosipbft/storage_test.go
  consensus/mod.go
  consensus/mod_test.go
  cosi/blscosi/handler.go
  cosi/blscosi/mod.go
  cosi/mod.go
  encoding/errors.go
  encoding/mod.go
  go.mod
  go.sum
  mino/messages.pb.go
  mino/messages.proto
  mino/minoch/address.go
  mino/minoch/address_test.go
  mino/minoch/manager.go
  mino/minoch/mod.go
  mino/minoch/mod_test.go
  mino/minoch/rpc.go
  mino/minoch/rpc_test.go
  mino/minogrpc/mod.go
  mino/minogrpc/mod_test.go
  mino/minogrpc/overlay.pb.go
  mino/minogrpc/overlay.proto
  mino/minogrpc/server.go
  mino/minogrpc/server_test.go
  mino/mod.go
Labels: WIP

#7 Hash module
  Makefile
  README.md
  blockchain/skipchain/messages.pb.go
  consensus/cosipbft/forward_link.go
  consensus/cosipbft/forward_link_test.go
  consensus/cosipbft/messages.pb.go
  consensus/cosipbft/mod.go
  consensus/cosipbft/mod_test.go
  consensus/cosipbft/queue.go
  consensus/cosipbft/queue_test.go
  cosi/blscosi/messages.pb.go
  crypto/bls/messages.pb.go
  crypto/mod.go
  go.mod
  go.sum
  mino/minogrpc/overlay.pb.go
Labels: enhancement

#8 Refactor cosi interface
  blockchain/mod.go
  blockchain/skipchain/block.go
  blockchain/skipchain/block_test.go
  blockchain/skipchain/handler.go
  blockchain/skipchain/member.go
  blockchain/skipchain/mod.go
  blockchain/skipchain/mod_test.go
  consensus/cosipbft/forward_link.go
  consensus/cosipbft/forward_link_test.go
  consensus/cosipbft/messages.pb.go
  consensus/cosipbft/messages.proto
  consensus/cosipbft/mod.go
  consensus/cosipbft/mod_test.go
  consensus/cosipbft/queue.go
  consensus/cosipbft/queue_test.go
  consensus/cosipbft/requests.go
  consensus/mod.go
  cosi/blscosi/mod.go
  cosi/mod.go
  crypto/bls/mod.go
  crypto/mod.go
  mino/minoch/manager.go
  mino/minoch/rpc.go
  mino/minoch/rpc_test.go
  mino/minogrpc/server.go
  mino/minogrpc/server_test.go
  mino/mod.go
Labels: enhancement

#6 Adds a first draft with grpc stream
  .gitignore
  go.mod
  mino/minogrpc/mod.go
  mino/minogrpc/mod_test.go
  mino/minogrpc/overlay.go
  mino/minogrpc/overlay.pb.go
  mino/minogrpc/overlay.proto
  mino/minogrpc/overlay_test.go
  mino/minogrpc/server.go
  mino/minogrpc/server_test.go
  mino/mod.go
Labels: Mino

#9 Cosi unit tests
  README.md
  blockchain/skipchain/block.go
  blockchain/skipchain/block_test.go
  blockchain/skipchain/member.go
  blockchain/skipchain/mod_test.go
  consensus/cosipbft/forward_link_test.go
  consensus/cosipbft/messages.pb.go
  consensus/cosipbft/mod.go
  consensus/cosipbft/mod_test.go
  cosi/blscosi/mod.go
  cosi/flatcosi/handler.go
  cosi/flatcosi/handler_test.go
  cosi/flatcosi/messages.pb.go
  cosi/flatcosi/messages.proto
  cosi/flatcosi/mod.go
  cosi/flatcosi/mod_test.go
  cosi/mod.go
  crypto/bls/mod.go
  crypto/bls/mod_test.go
  crypto/mod.go
  encoding/errors.go
  encoding/errors_test.go
  encoding/mod_test.go
  go.sum
  internal/testing/mod.go
Labels: enhancement

#11 Adds test for proto messages
  mino/minogrpc/mod_test.go
Labels: Mino

#10 Actorify the consensus to follow cosi
  blockchain/mod.go
  blockchain/skipchain/mod.go
  blockchain/skipchain/mod_test.go
  consensus/cosipbft/mod.go
  consensus/cosipbft/mod_test.go
  consensus/mod.go
Labels: enhancement

#15 Update guideline for comments for interface implementation.
  docs/guideline.md
Labels: R4M 🚀

#13 Improves stream
  consensus/cosipbft/forward_link_test.go
  consensus/cosipbft/storage_test.go
  cosi/flatcosi/handler_test.go
  cosi/flatcosi/mod_test.go
  crypto/bls/mod_test.go
  docs/guideline.md
  encoding/mod_test.go
  go.mod
  mino/minoch/rpc.go
  mino/minoch/rpc_test.go
  mino/minogrpc/mod.go
  mino/minogrpc/mod_test.go
  mino/minogrpc/overlay.go
  mino/minogrpc/overlay.pb.go
  mino/minogrpc/overlay_test.go
  mino/minogrpc/server.go
  mino/minogrpc/server_test.go
  mino/mod.go
Labels: Mino, R4M 🚀

#14 QSC initial implementation
  blockchain/skipchain/member.go
  blockchain/skipchain/messages.pb.go
  consensus/cosipbft/messages.pb.go
  consensus/qsc/broadcast.go
  consensus/qsc/broadcast_test.go
  consensus/qsc/history.go
  consensus/qsc/history_test.go
  consensus/qsc/messages.pb.go
  consensus/qsc/messages.proto
  consensus/qsc/mod.go
  consensus/qsc/mod_test.go
  cosi/flatcosi/messages.pb.go
  crypto/bls/messages.pb.go
  go.mod
  go.sum
  mino/minoch/mod.go
  mino/minoch/rpc.go
  mino/minoch/rpc_test.go
  mino/minogrpc/mod_test.go
  mino/minogrpc/overlay.pb.go
  mino/minogrpc/server_test.go
  mino/mod.go
  mino/mod_test.go
  mino/option.go
  mino/option_test.go
  mod.go
Labels: R4M 🚀

#16 Skipchain unit tests
  blockchain/mod.go
  blockchain/skipchain/block.go
  blockchain/skipchain/block_test.go
  blockchain/skipchain/db.go
  blockchain/skipchain/handler.go
  blockchain/skipchain/handler_test.go
  blockchain/skipchain/member.go
  blockchain/skipchain/messages.pb.go
  blockchain/skipchain/messages.proto
  blockchain/skipchain/mod.go
  blockchain/skipchain/mod_test.go
  blockchain/skipchain/validator.go
  blockchain/skipchain/validator_test.go
  consensus/cosipbft/forward_link.go
  consensus/cosipbft/forward_link_test.go
  consensus/cosipbft/messages.pb.go
  consensus/mod.go
  consensus/qsc/messages.pb.go
  cosi/flatcosi/messages.pb.go
  crypto/bls/messages.pb.go
  mino/minogrpc/overlay.pb.go
Labels: R4M 🚀

#17 Close consensus executions
  consensus/cosipbft/mod.go
  consensus/cosipbft/mod_test.go
  consensus/mod.go
  consensus/qsc/mod.go
  consensus/qsc/mod_test.go
Labels: R4M 🚀, enhancement

#18 Skipchain validator buffer
  blockchain/skipchain/mod.go
  blockchain/skipchain/validator.go
  blockchain/skipchain/validator_test.go
  consensus/qsc/mod.go
  consensus/qsc/mod_test.go
Labels: R4M 🚀, enhancement

#20 Skipchain watch
  blockchain/mod.go
  blockchain/skipchain/mod.go
  blockchain/skipchain/mod_test.go
  blockchain/skipchain/validator.go
  blockchain/skipchain/validator_test.go
  blockchain/watcher_test.go
Labels: R4M 🚀, enhancement

#21 Skipchain conodes unit tests
  blockchain/skipchain/block.go
  blockchain/skipchain/block_test.go
  blockchain/skipchain/conode.go
  blockchain/skipchain/conode_test.go
  blockchain/skipchain/messages.pb.go
  blockchain/skipchain/messages.proto
  consensus/cosipbft/messages.pb.go
  consensus/qsc/messages.pb.go
  consensus/qsc/mod_test.go
  cosi/flatcosi/messages.pb.go
  crypto/bls/messages.pb.go
  mino/minogrpc/overlay.pb.go
Labels: R4M 🚀, enhancement

#23 Skipchain: use the crypto rand interface
  blockchain/skipchain/mod.go
  blockchain/skipchain/mod_test.go
  crypto/mod.go
  crypto/rand.go
  crypto/rand_test.go
Labels: R4M 🚀, enhancement

#22 Skipchain: atomic commit
  blockchain/skipchain/db.go
  blockchain/skipchain/db_test.go
  blockchain/skipchain/handler_test.go
  blockchain/skipchain/mod_test.go
  blockchain/skipchain/validator.go
  blockchain/skipchain/validator_test.go
Labels: R4M 🚀, enhancement

#24 RPC: add a context for cancellation
  blockchain/skipchain/mod.go
  blockchain/skipchain/mod_test.go
  consensus/cosipbft/mod.go
  consensus/cosipbft/mod_test.go
  consensus/qsc/broadcast.go
  consensus/qsc/broadcast_test.go
  cosi/flatcosi/mod.go
  cosi/flatcosi/mod_test.go
  cosi/mod.go
  mino/minoch/rpc.go
  mino/minoch/rpc_test.go
  mino/minogrpc/server.go
  mino/minogrpc/server_test.go
  mino/mod.go
Labels: R4M 🚀, enhancement

#19 minogrpc: Implements message relaying
  go.mod
  mino/minogrpc/overlay.go
  mino/minogrpc/overlay.pb.go
  mino/minogrpc/overlay_test.go
  mino/minogrpc/server.go
  mino/minogrpc/server_test.go
Labels: Mino, R4M 🚀

#25 Skipchain leader only
  blockchain/mod.go
  blockchain/skipchain/block.go
  blockchain/skipchain/block_test.go
  blockchain/skipchain/handler.go
  blockchain/skipchain/handler_test.go
  blockchain/skipchain/mod.go
  blockchain/skipchain/mod_test.go
  blockchain/skipchain/validator.go
  blockchain/skipchain/validator_test.go
  blockchain/viewchange/constant.go
  blockchain/viewchange/constant_test.go
  blockchain/viewchange/mod.go
  consensus/cosipbft/mod.go
  consensus/cosipbft/mod_test.go
  consensus/mod.go
  consensus/qsc/broadcast.go
  consensus/qsc/broadcast_test.go
  consensus/qsc/mod_test.go
  cosi/flatcosi/handler.go
  cosi/flatcosi/handler_test.go
  cosi/mod.go
  docs/introduction.md
  mino/minoch/address.go
  mino/minoch/address_test.go
  mino/minoch/mod.go
  mino/minoch/rpc.go
  mino/minogrpc/mod.go
  mino/minogrpc/mod_test.go
  mino/minogrpc/overlay.go
  mino/minogrpc/overlay_test.go
  mino/minogrpc/server_test.go
  mino/mod.go
  mino/mod_test.go
  mino/option.go
  mino/option_test.go
Labels: Mino, R4M 🚀, enhancement

#26 Skipchain: multiple inits create only one genesis block
  blockchain/skipchain/db.go
  blockchain/skipchain/db_test.go
  blockchain/skipchain/mod.go
  blockchain/skipchain/mod_test.go
  go.mod
Labels: R4M 🚀, enhancement

#29 Ledger inventory
  blockchain/mod.go
  blockchain/skipchain/mod_test.go
  blockchain/skipchain/validator.go
  blockchain/skipchain/validator_test.go
  crypto/hash.go
  crypto/hash_test.go
  ledger/byzcoin/messages.pb.go
  ledger/byzcoin/messages.proto
  ledger/byzcoin/mod.go
  ledger/byzcoin/mod_test.go
  ledger/byzcoin/transaction.go
  ledger/byzcoin/txproc.go
  ledger/byzcoin/txproc_test.go
  ledger/inventory/mem/mod.go
  ledger/inventory/mem/mod_test.go
  ledger/inventory/mod.go
  mino/minogrpc/overlay.pb.go
Labels: Byzcoin, R4M 🚀

#30 Skipchain genesis processing
  blockchain/skipchain/db.go
  blockchain/skipchain/db_test.go
  blockchain/skipchain/handler.go
  blockchain/skipchain/handler_test.go
  blockchain/skipchain/mod.go
  blockchain/skipchain/validator_test.go
  docs/introduction.md
  ledger/byzcoin/mod.go
  ledger/byzcoin/txproc.go
  ledger/byzcoin/txproc_test.go
  ledger/inventory/mem/mod.go
  ledger/inventory/mod.go
Labels: R4M 🚀, enhancement
