Repository dedis/dela, pull requests merged in 2020-08, with the labels that each got.

#83 Core: rename tap into txn for clarity
  core/execution/baremetal/mod.go
  core/execution/baremetal/mod_test.go
  core/execution/mod.go
  core/ordering/cosipbft/blocksync/default_test.go
  core/ordering/cosipbft/mod.go
  core/ordering/cosipbft/mod_test.go
  core/ordering/cosipbft/pbft/mod_test.go
  core/ordering/cosipbft/proc.go
  core/ordering/cosipbft/types/block.go
  core/ordering/cosipbft/types/block_test.go
  core/ordering/pow/mod.go
  core/ordering/pow/mod_test.go
  core/txn/anon/json/mod.go
  core/txn/anon/json/mod_test.go
  core/txn/anon/mod.go
  core/txn/anon/mod_test.go
  core/txn/mod.go
  core/txn/pool/gossip/mod.go
  core/txn/pool/gossip/mod_test.go
  core/txn/pool/mem/mod.go
  core/txn/pool/mem/mod_test.go
  core/txn/pool/mod.go
  core/validation/mod.go
  core/validation/simple/data.go
  core/validation/simple/data_test.go
  core/validation/simple/json/mod.go
  core/validation/simple/mod.go
  core/validation/simple/mod_test.go
  serde/json/mod.go
Labels: R4M 🚀, enhancement

#84 Core: view change as a transaction
  consensus/cosipbft/types/queue_test.go
  consensus/viewchange/mod.go
  consensus/viewchange/roster/changeset.go
  core/execution/baremetal/mod.go
  core/execution/baremetal/mod_test.go
  core/execution/baremetal/viewchange/mod.go
  core/execution/baremetal/viewchange/mod_test.go
  core/ordering/cosipbft/blockstore/mem_test.go
  core/ordering/cosipbft/blocksync/default_test.go
  core/ordering/cosipbft/blocksync/types/mod_test.go
  core/ordering/cosipbft/json/link.go
  core/ordering/cosipbft/json/mod.go
  core/ordering/cosipbft/mod.go
  core/ordering/cosipbft/mod_test.go
  core/ordering/cosipbft/pbft/mod.go
  core/ordering/cosipbft/pbft/mod_test.go
  core/ordering/cosipbft/proc.go
  core/ordering/cosipbft/proc_test.go
  core/ordering/cosipbft/types/block.go
  core/ordering/cosipbft/types/block_test.go
  core/ordering/cosipbft/types/messages.go
  core/ordering/cosipbft/types/messages_test.go
  core/ordering/cosipbft/types/mod.go
  core/ordering/pow/mod_test.go
Labels: R4M 🚀, enhancement

#78 Enables the calypso GUI
  cli/node/memcoin/mod.go
  go.mod
  go.sum
  mino/proxy/http/mod_test.go
Labels: UI

#85 Make synchronizer easier to use
  core/ordering/cosipbft/blocksync/default.go
  core/ordering/cosipbft/blocksync/default_test.go
  core/ordering/cosipbft/blocksync/mod.go
  core/ordering/cosipbft/mod.go
  core/ordering/cosipbft/mod_test.go
  core/ordering/cosipbft/proc_test.go
Labels: R4M 🚀, enhancement

#86 Make transaction pool easier to use
  core/ordering/cosipbft/mod.go
  core/ordering/cosipbft/mod_test.go
  core/ordering/pow/mod.go
  core/txn/pool/gatherer.go
  core/txn/pool/gatherer_test.go
  core/txn/pool/gossip/mod.go
  core/txn/pool/gossip/mod_test.go
  core/txn/pool/mem/mod.go
  core/txn/pool/mem/mod_test.go
  core/txn/pool/mod.go
Labels: R4M 🚀, enhancement

#87 Graceful close of the ordering service
  core/ordering/cosipbft/mod.go
  core/ordering/cosipbft/mod_test.go
  core/store/kv/default.go
  core/store/kv/default_test.go
  core/store/kv/mod.go
  core/txn/pool/gatherer.go
  core/txn/pool/gatherer_test.go
  core/txn/pool/gossip/mod.go
  core/txn/pool/gossip/mod_test.go
  core/txn/pool/mem/mod.go
  core/txn/pool/mem/mod_test.go
Labels: R4M 🚀, enhancement

#90 Update guideline.md
  docs/guideline.md
Labels: documentation

#88 Core: use db transaction when required
  core/ordering/cosipbft/blockstore/mem.go
  core/ordering/cosipbft/blockstore/mem_test.go
  core/ordering/cosipbft/blockstore/mod.go
  core/ordering/cosipbft/mod.go
  core/ordering/cosipbft/mod_test.go
  core/ordering/cosipbft/pbft/mod.go
  core/ordering/cosipbft/pbft/mod_test.go
  core/ordering/cosipbft/proc.go
  core/ordering/cosipbft/proc_test.go
  core/store/hashtree/binprefix/disk.go
  core/store/hashtree/binprefix/disk_test.go
  core/store/hashtree/binprefix/mod.go
  core/store/hashtree/binprefix/mod_test.go
  core/store/hashtree/binprefix/tree_test.go
  core/store/hashtree/mod.go
  core/store/kv/default.go
  core/store/kv/default_test.go
  core/store/kv/mod.go
  core/store/mod.go
Labels: R4M 🚀, enhancement
