Repository dedis/dela, pull requests merged in 2020-09, with the labels that each got.

#91 Implement the proof interface
  core/execution/baremetal/viewchange/mod_test.go
  core/ordering/cosipbft/blockstore/mem.go
  core/ordering/cosipbft/blockstore/mem_test.go
  core/ordering/cosipbft/blockstore/mod.go
  core/ordering/cosipbft/blockstore/tree_test.go
  core/ordering/cosipbft/blocksync/default.go
  core/ordering/cosipbft/blocksync/default_test.go
  core/ordering/cosipbft/blocksync/json/mod.go
  core/ordering/cosipbft/blocksync/json/mod_test.go
  core/ordering/cosipbft/blocksync/types/mod.go
  core/ordering/cosipbft/blocksync/types/mod_test.go
  core/ordering/cosipbft/json/chain.go
  core/ordering/cosipbft/json/link.go
  core/ordering/cosipbft/json/mod.go
  core/ordering/cosipbft/mod.go
  core/ordering/cosipbft/mod_test.go
  core/ordering/cosipbft/pbft/mod.go
  core/ordering/cosipbft/pbft/mod_test.go
  core/ordering/cosipbft/proc.go
  core/ordering/cosipbft/proc_test.go
  core/ordering/cosipbft/proof.go
  core/ordering/cosipbft/proof_test.go
  core/ordering/cosipbft/types/block.go
  core/ordering/cosipbft/types/block_test.go
  core/ordering/cosipbft/types/chain.go
  core/ordering/cosipbft/types/chain_test.go
  core/ordering/cosipbft/types/messages.go
  core/ordering/cosipbft/types/mod.go
  core/store/hashtree/binprefix/disk_test.go
  core/store/hashtree/binprefix/mod_test.go
  core/store/hashtree/binprefix/tree_test.go
  core/txn/anon/json/mod_test.go
  core/txn/pool/gatherer_test.go
  core/txn/pool/gossip/mod_test.go
  internal/testing/fake/mod.go
Labels: R4M 🚀, enhancement

#92 Core: json format tests for cosipbft
  core/ordering/cosipbft/blockstore/genesis.go
  core/ordering/cosipbft/blockstore/genesis_test.go
  core/ordering/cosipbft/blockstore/mod.go
  core/ordering/cosipbft/blocksync/default_test.go
  core/ordering/cosipbft/json/chain.go
  core/ordering/cosipbft/json/chain_test.go
  core/ordering/cosipbft/json/link.go
  core/ordering/cosipbft/json/link_test.go
  core/ordering/cosipbft/json/mod.go
  core/ordering/cosipbft/json/mod_test.go
  core/ordering/cosipbft/mod.go
  core/ordering/cosipbft/mod_test.go
  core/ordering/cosipbft/proc.go
  core/ordering/cosipbft/proc_test.go
  core/ordering/cosipbft/proof_test.go
  core/ordering/cosipbft/types/block.go
  core/ordering/cosipbft/types/block_test.go
  core/ordering/cosipbft/types/chain_test.go
Labels: R4M 🚀, enhancement

#95 Move the arc package
  cli/node/memcoin/mod.go
  core/access/darc/expr.go
  core/access/darc/expr_test.go
  core/access/darc/mod.go
  core/access/darc/mod_test.go
  core/access/mod.go
  core/access/mod_test.go
  core/txn/anon/mod.go
  core/txn/mod.go
  go.mod
  go.sum
  internal/testing/fake/mod.go
  mino/proxy/http/controller/mod_test.go
Labels: R4M 🚀, enhancement

#96 Core: add a controller to cosipbft
  cli/flag.go
  cli/mod.go
  cli/node/builder.go
  cli/node/builder_test.go
  cli/node/daemon.go
  cli/node/daemon_test.go
  cli/node/flagset.go
  cli/node/flagset_test.go
  cli/node/memcoin/mod.go
  cli/node/memcoin/mod_test.go
  cli/node/mod.go
  core/execution/baremetal/viewchange/mod.go
  core/execution/baremetal/viewchange/mod_test.go
  core/ordering/cosipbft/controller/action.go
  core/ordering/cosipbft/controller/action_test.go
  core/ordering/cosipbft/controller/mod.go
  core/ordering/cosipbft/controller/mod_test.go
  core/ordering/cosipbft/mod.go
  core/ordering/cosipbft/mod_test.go
  core/txn/anon/mod.go
  core/txn/anon/mod_test.go
  core/txn/mod.go
  core/txn/pool/gatherer.go
  core/txn/pool/gatherer_test.go
  core/txn/pool/gossip/mod.go
  core/txn/pool/gossip/mod_test.go
  core/txn/pool/mem/mod.go
  core/txn/pool/mem/mod_test.go
  core/txn/pool/mod.go
  core/validation/simple/data.go
  core/validation/simple/json/mod.go
  core/validation/simple/mod.go
  crypto/bls/mod.go
  crypto/bls/mod_test.go
  crypto/ed25519/mod.go
  crypto/ed25519/mod_test.go
  crypto/mod.go
  dkg/pedersen/controller/mod.go
  go.mod
  go.sum
  internal/testing/fake/mod.go
  mino/minogrpc/controller/actions.go
  mino/minogrpc/controller/actions_test.go
  mino/minogrpc/rpc.go
  mino/minogrpc/server.go
  mino/proxy/http/controller/mod_test.go
Labels: R4M 🚀, enhancement

#98 Crypto: fix a todo in bls
  crypto/bls/json/mod.go
  crypto/bls/json/mod_test.go
Labels: R4M 🚀, enhancement

#97 Cosi: fix a todo in threshold
  cosi/threshold/signature.go
  cosi/threshold/signature_test.go
  internal/testing/fake/mod.go
Labels: R4M 🚀, enhancement

#99 Improve the transactions
  cli/node/memcoin/mod.go
  cli/node/memcoin/mod_test.go
  core/execution/baremetal/viewchange/mod_test.go
  core/ordering/cosipbft/blockstore/mem.go
  core/ordering/cosipbft/blocksync/default_test.go
  core/ordering/cosipbft/controller/action.go
  core/ordering/cosipbft/controller/action_test.go
  core/ordering/cosipbft/controller/mod.go
  core/ordering/cosipbft/mod.go
  core/ordering/cosipbft/mod_test.go
  core/ordering/cosipbft/types/block_test.go
  core/ordering/mod.go
  core/ordering/pow/mod_test.go
  core/txn/anon/json/mod_test.go
  core/txn/mod.go
  core/txn/pool/gossip/mod_test.go
  core/txn/signed/controller/mod.go
  core/txn/signed/json/mod.go
  core/txn/signed/json/mod_test.go
  core/txn/signed/mod.go
  core/txn/signed/mod_test.go
  core/validation/simple/data_test.go
  core/validation/simple/mod.go
  core/validation/simple/mod_test.go
  crypto/common/mod.go
  crypto/common/mod_test.go
  internal/testing/fake/mod.go
  serde/json/mod.go
Labels: R4M 🚀, enhancement

#100 Core: pbft view are now signed
  cli/node/memcoin/mod_test.go
  core/ordering/cosipbft/json/link.go
  core/ordering/cosipbft/json/link_test.go
  core/ordering/cosipbft/json/mod.go
  core/ordering/cosipbft/json/mod_test.go
  core/ordering/cosipbft/mod.go
  core/ordering/cosipbft/mod_test.go
  core/ordering/cosipbft/pbft/mod.go
  core/ordering/cosipbft/pbft/mod_test.go
  core/ordering/cosipbft/pbft/view.go
  core/ordering/cosipbft/pbft/view_test.go
  core/ordering/cosipbft/proc.go
  core/ordering/cosipbft/proc_test.go
  core/ordering/cosipbft/types/chain.go
  core/ordering/cosipbft/types/messages.go
  core/ordering/cosipbft/types/messages_test.go
Labels: R4M 🚀, enhancement

#101 Core: contract returns an error displayed in the tx result
  cli/node/memcoin/mod_test.go
  core/execution/baremetal/mod.go
  core/execution/baremetal/mod_test.go
  core/execution/baremetal/viewchange/mod.go
  core/execution/baremetal/viewchange/mod_test.go
  core/ordering/cosipbft/mod_test.go
  core/ordering/pow/mod_test.go
  core/validation/simple/mod.go
Labels: R4M 🚀, enhancement

#89 Use the new Router interface
  dkg/pedersen/handler.go
  dkg/pedersen/handler_test.go
  dkg/pedersen/mod.go
  dkg/pedersen/mod_test.go
  go.mod
  internal/testing/fake/mod.go
  internal/traffic/mod.go
  internal/traffic/mod_test.go
  mino/minogrpc/controller/mod.go
  mino/minogrpc/mod.go
  mino/minogrpc/mod_test.go
  mino/minogrpc/ptypes/mod.go
  mino/minogrpc/ptypes/overlay.pb.go
  mino/minogrpc/ptypes/overlay.proto
  mino/minogrpc/routing/json/mod.go
  mino/minogrpc/routing/json/mod_test.go
  mino/minogrpc/routing/routing.go
  mino/minogrpc/routing/routing_test.go
  mino/minogrpc/rpc.go
  mino/minogrpc/rpc_test.go
  mino/minogrpc/server.go
  mino/minogrpc/server_test.go
  mino/minogrpc/session/mod.go
  mino/minogrpc/session/mod_test.go
  mino/minogrpc/session/queue.go
  mino/minogrpc/stream.go
  mino/minogrpc/stream_test.go
  mino/minogrpc/traffic.go
  mino/minogrpc/traffic_test.go
  mino/router/mod.go
  mino/router/tree/json/mod.go
  mino/router/tree/mod.go
  mino/router/tree/mod_test.go
  mino/router/tree/tree.go
  mino/router/tree/tree_test.go
  mino/router/tree/types/handshake.go
  mino/router/tree/types/handshake_test.go
  mino/router/tree/types/mod.go
  mino/router/tree/types/packet.go
  mino/router/tree/types/packet_test.go
  serde/json/mod.go
Labels: Mino, R4M 🚀

#103 Fix cosipbft issue
  core/ordering/cosipbft/blockstore/mod.go
  core/ordering/cosipbft/blockstore/tree.go
  core/ordering/cosipbft/blockstore/tree_test.go
  core/ordering/cosipbft/mod.go
  core/ordering/cosipbft/mod_test.go
  core/ordering/cosipbft/pbft/mod.go
Labels: R4M 🚀, bug

#102 Adds minor updates on mcheck
  cli/node/memcoin/mod.go
  core/store/hashtree/binprefix/mod.go
  core/store/hashtree/binprefix/tree.go
  core/txn/signed/mod.go
  internal/mcheck/mod.go
  internal/mcheck/mod_test.go
  internal/mcheck/testdata/src/comment/mod1.go
  internal/mcheck/testdata/src/ifcheck/mod2.go
Labels: R4M 🚀

#104 Minogrpc: use the routing failure call
  Makefile
  dkg/pedersen/handler.go
  dkg/pedersen/handler_test.go
  dkg/pedersen/mod.go
  dkg/pedersen/mod_test.go
  internal/traffic/mod.go
  internal/traffic/mod_test.go
  mino/minogrpc/controller/mod_test.go
  mino/minogrpc/mod.go
  mino/minogrpc/mod_test.go
  mino/minogrpc/ptypes/overlay.pb.go
  mino/minogrpc/ptypes/overlay.proto
  mino/minogrpc/rpc.go
  mino/minogrpc/rpc_test.go
  mino/minogrpc/server.go
  mino/minogrpc/server_test.go
  mino/minogrpc/session/mod.go
  mino/minogrpc/session/mod_test.go
  mino/router/mod.go
  mino/router/tree/mod.go
  mino/router/tree/mod_test.go
  mino/router/tree/tree.go
  mino/router/tree/tree_test.go
  mod.go
Labels: Mino, R4M 🚀

#105 Minogrpc: memory management for the queue
  mino/minogrpc/session/mod.go
  mino/minogrpc/session/queue.go
  mino/minogrpc/session/queue_test.go
Labels: Mino, R4M 🚀

#106 Minogrpc: allow port 0
  dkg/pedersen/mod_test.go
  mino/minogrpc/addr.go
  mino/minogrpc/addr_test.go
  mino/minogrpc/controller/mod.go
  mino/minogrpc/mod.go
  mino/minogrpc/mod_test.go
  mino/minogrpc/server_test.go
Labels: Mino, R4M 🚀

#107 Minogrpc: session with multiple parents
  mino/minogrpc/rpc.go
  mino/minogrpc/server.go
  mino/minogrpc/server_test.go
  mino/minogrpc/session/mod.go
  mino/minogrpc/session/mod_test.go
Labels: Mino, R4M 🚀

#117 Core: signature to the transactions
  core/ordering/cosipbft/mod_test.go
  core/txn/pool/gossip/mod_test.go
  core/txn/signed/json/mod.go
  core/txn/signed/json/mod_test.go
  core/txn/signed/mod.go
  core/txn/signed/mod_test.go
  internal/testing/fake/mod.go
  mod.go
Labels: R4M 🚀, enhancement

#110 Minogrpc: check queue error
  mino/minogrpc/session/mod.go
  mino/minogrpc/session/mod_test.go
Labels: Mino, R4M 🚀

#109 Disable logging and allow to set the level with an env variable
  core/ordering/cosipbft/mod_test.go
  mod.go
Labels: R4M 🚀, enhancement

#111 Router: add test to the json package
  mino/router/tree/json/mod.go
  mino/router/tree/json/mod_test.go
  mino/router/tree/mod.go
  mino/router/tree/mod_test.go
  mino/router/tree/types/handshake.go
  mino/router/tree/types/handshake_test.go
Labels: Mino, R4M 🚀

#108 Access: permissioned view change
  core/access/credentials.go
  core/access/credentials_test.go
  core/access/darc/expr.go
  core/access/darc/expr_test.go
  core/access/darc/json/mod.go
  core/access/darc/json/mod_test.go
  core/access/darc/mod.go
  core/access/darc/mod_test.go
  core/access/darc/types/expr.go
  core/access/darc/types/expr_test.go
  core/access/darc/types/mod.go
  core/access/darc/types/permission.go
  core/access/darc/types/permission_test.go
  core/access/mod.go
  core/access/mod_test.go
  core/execution/baremetal/mod.go
  core/execution/baremetal/viewchange/mod.go
  core/execution/baremetal/viewchange/mod_test.go
  core/ordering/cosipbft/controller/mod.go
  core/ordering/cosipbft/mod.go
  core/ordering/cosipbft/mod_test.go
  core/ordering/cosipbft/proc.go
  core/ordering/cosipbft/proc_test.go
  core/txn/signed/controller/mod.go
  crypto/bls/mod.go
  crypto/ed25519/mod.go
  crypto/mod.go
  internal/testing/fake/mod.go
  serde/json/mod.go
Labels: R4M 🚀, enhancement

#112 Mino: documentation
  docs/mino.md
  docs/sidebar.md
  mino/README.md
  mino/mod.go
Labels: R4M 🚀, documentation

#113 Core: persistent stores
  cli/node/memcoin/mod_test.go
  core/ordering/cosipbft/blockstore/disk.go
  core/ordering/cosipbft/blockstore/disk_test.go
  core/ordering/cosipbft/blockstore/genesis.go
  core/ordering/cosipbft/blockstore/genesis_test.go
  core/ordering/cosipbft/blockstore/mem_test.go
  core/ordering/cosipbft/blocksync/default.go
  core/ordering/cosipbft/blocksync/default_test.go
  core/ordering/cosipbft/controller/mod.go
  core/ordering/cosipbft/controller/mod_test.go
  core/ordering/cosipbft/mod.go
  core/ordering/cosipbft/mod_test.go
  core/ordering/cosipbft/pbft/mod.go
  core/ordering/cosipbft/pbft/mod_test.go
  core/ordering/cosipbft/proc.go
  core/store/hashtree/binprefix/disk.go
  core/store/hashtree/binprefix/disk_test.go
  core/store/hashtree/binprefix/mod.go
  core/store/hashtree/binprefix/mod_test.go
  core/store/hashtree/binprefix/path.go
  core/store/hashtree/binprefix/path_test.go
  core/store/hashtree/binprefix/tree.go
  core/store/hashtree/binprefix/tree_test.go
  crypto/bls/mod.go
  crypto/bls/mod_test.go
  mino/minoch/rpc.go
  mino/minogrpc/rpc.go
  mino/minogrpc/server.go
  mino/minogrpc/server_test.go
Labels: R4M 🚀, enhancement

#115 Core: use a thresholded collective signing
  cli/node/memcoin/mod_test.go
  core/ordering/cosipbft/blocksync/default.go
  core/ordering/cosipbft/blocksync/default_test.go
  core/ordering/cosipbft/controller/mod.go
  core/ordering/cosipbft/mod.go
  core/ordering/cosipbft/mod_test.go
  cosi/flatcosi/mod.go
  cosi/mod.go
  cosi/threshold/actor.go
  cosi/threshold/actor_test.go
  cosi/threshold/handler_test.go
  cosi/threshold/json/mod.go
  cosi/threshold/json/mod_test.go
  cosi/threshold/mod.go
  cosi/threshold/mod_test.go
  cosi/threshold/types/mod.go
  cosi/threshold/types/mod_test.go
  internal/testing/fake/mod.go
  mino/gossip/flat.go
  mino/gossip/flat_test.go
  serde/json/mod.go
Labels: R4M 🚀, enhancement

#118 Github workflow: use trace level for logs
  .github/workflows/go_test.yml
Labels: R4M 🚀, enhancement

#119 Cosipbft: use a different timeout after a failure
  core/ordering/cosipbft/mod.go
  core/ordering/cosipbft/mod_test.go
  core/ordering/cosipbft/pbft/mod.go
Labels: R4M 🚀, enhancement

#121 Fix test after merges
  core/ordering/cosipbft/mod.go
  core/ordering/cosipbft/mod_test.go
Labels: R4M 🚀, bug

#120 Cosipbft: backoff on failure but keep running
  core/ordering/cosipbft/mod.go
  core/ordering/cosipbft/mod_test.go
  internal/testing/fake/mod.go
Labels: R4M 🚀, enhancement

#122 Fix minogrpc test
  mino/minogrpc/mod_test.go
Labels: R4M 🚀, bug

#114 CLI: adds a stop routine to initializers
  cli/node/builder.go
  cli/node/builder_test.go
  cli/node/daemon_test.go
  cli/node/memcoin/mod_test.go
  cli/node/mod.go
  core/ordering/cosipbft/controller/action_test.go
  core/ordering/cosipbft/controller/mod.go
  core/ordering/cosipbft/controller/mod_test.go
  core/ordering/cosipbft/mod.go
  core/ordering/mod.go
  core/store/hashtree/binprefix/tree.go
  core/txn/pool/gatherer.go
  core/txn/pool/gossip/mod.go
  core/txn/pool/gossip/mod_test.go
  core/txn/pool/mem/mod.go
  core/txn/pool/mod.go
  core/txn/signed/controller/mod.go
  dkg/pedersen/controller/mod.go
  dkg/pedersen/controller/mod_test.go
  mino/minogrpc/controller/mod.go
  mino/minogrpc/controller/mod_test.go
  mino/proxy/http/controller/mod.go
  mino/proxy/http/controller/mod_test.go
Labels: R4M 🚀, enhancement

#124 ViewChange: check only one tx per block
  core/execution/baremetal/mod.go
  core/execution/baremetal/mod_test.go
  core/execution/baremetal/viewchange/mod.go
  core/execution/baremetal/viewchange/mod_test.go
  core/execution/mod.go
  core/ordering/cosipbft/mod_test.go
  core/ordering/cosipbft/pbft/mod_test.go
  core/ordering/pow/mod_test.go
  core/txn/pool/gossip/mod_test.go
  core/validation/simple/mod.go
  core/validation/simple/mod_test.go
Labels: R4M 🚀, enhancement

#123 Pool: improve memory management
  core/ordering/cosipbft/controller/action_test.go
  core/ordering/cosipbft/mod.go
  core/ordering/cosipbft/mod_test.go
  core/txn/mod.go
  core/txn/pool/gatherer.go
  core/txn/pool/gatherer_test.go
  core/txn/pool/gossip/mod.go
  core/txn/pool/gossip/mod_test.go
  core/txn/pool/mem/mod.go
  core/txn/pool/mem/mod_test.go
  core/txn/pool/mod.go
  core/txn/signed/controller/mod.go
  core/validation/mod.go
  core/validation/simple/mod.go
  core/validation/simple/mod_test.go
Labels: R4M 🚀, enhancement
