Repository dedis/dela, pull requests merged in 2020-07, with the labels that each got.

#69 Mino: fix sync of responses and errors with Call
  blockchain/skipchain/mod.go
  blockchain/skipchain/mod_test.go
  blockchain/skipchain/ops_test.go
  consensus/cosipbft/mod.go
  consensus/cosipbft/mod_test.go
  consensus/qsc/broadcast.go
  consensus/qsc/broadcast_test.go
  consensus/qsc/mod.go
  cosi/flatcosi/handler_test.go
  cosi/flatcosi/mod.go
  cosi/flatcosi/mod_test.go
  cosi/threshold/actor_test.go
  dkg/pedersen/mod_test.go
  internal/testing/fake/mod.go
  mino/gossip/flat.go
  mino/gossip/flat_test.go
  mino/minoch/rpc.go
  mino/minoch/rpc_test.go
  mino/minogrpc/rpc.go
  mino/minogrpc/rpc_test.go
  mino/mod.go
  mino/response.go
  mino/response_test.go
Labels: Mino, R4M 🚀, bug, enhancement

#71 Minogrpc now provides the source address of a Call
  internal/testing/fake/mod.go
  mino/minogrpc/rpc.go
  mino/minogrpc/rpc_test.go
  mino/minogrpc/server_test.go
Labels: Mino, R4M 🚀, enhancement

#70 Update serde documentation
  docs/assets/serde.png
  docs/diagrams/serde.drawio
  docs/serde.md
  serde/mod.go
  serde/serde.drawio
Labels: R4M 🚀, documentation

#72 Adds unit tests for ed25519
  crypto/bls/mod_test.go
  crypto/ed25519/json/mod.go
  crypto/ed25519/json/mod_test.go
  crypto/ed25519/mod.go
  crypto/ed25519/mod_test.go
Labels: R4M 🚀, enhancement

#73 Adds unit tests for calypso/json
  Makefile
  calypso/json/mod_test.go
  internal/testing/fake/mod.go
Labels: R4M 🚀, enhancement

#76 Moves Calypso and adds httpclient
  calypso/calypso.go
  calypso/calypso_test.go
  calypso/json/mod.go
  calypso/json/mod_test.go
  calypso/mod.go
  calypso/storage/inmemory/mod.go
  calypso/storage/mod.go
  cli/node/injector.go
  cli/node/injector_test.go
  cli/node/memcoin/mod.go
  cli/node/mod.go
  crypto/ed25519/mod.go
  dkg/pedersen/controller/mod.go
  dkg/pedersen/controller/mod_test.go
  dkg/pedersen/json/mod_test.go
  dkg/pedersen/mod.go
  dkg/pedersen/mod_test.go
  go.mod
  go.sum
  ledger/byzcoin/controller/mod.go
  mino/addr.go
  mino/proxy/http/controller/mod.go
  mino/proxy/http/controller/mod_test.go
  mino/proxy/http/mod.go
  mino/proxy/http/mod_test.go
  mino/proxy/mod.go
  serde/json/mod.go
Labels: R4M 🚀, enhancement

#75 Ledger refactoring
  core/execution/baremetal/mod.go
  core/execution/baremetal/mod_test.go
  core/execution/mod.go
  core/ordering/mod.go
  core/ordering/pow/block.go
  core/ordering/pow/block_test.go
  core/ordering/pow/mod.go
  core/ordering/pow/mod_test.go
  core/ordering/pow/observer.go
  core/ordering/pow/proof.go
  core/store/mod.go
  core/store/trie/mem/mod.go
  core/store/trie/mem/mod_test.go
  core/store/trie/mem/share.go
  core/store/trie/mod.go
  core/tap/anon/mod.go
  core/tap/anon/mod_test.go
  core/tap/mod.go
  core/tap/pool/mem/mod.go
  core/tap/pool/mem/mod_test.go
  core/tap/pool/mod.go
  core/validation/mod.go
  core/validation/simple/data.go
  core/validation/simple/data_test.go
  core/validation/simple/mod.go
  core/validation/simple/mod_test.go
  docs/diagrams/ledger.drawio
  internal/testing/fake/mod.go
  mino/minogrpc/certs/mem_test.go
Labels: R4M 🚀

#77 Merkle tree
  core/ordering/pow/mod.go
  core/ordering/pow/mod_test.go
  core/ordering/pow/proof.go
  core/store/hashtree/mem/mod.go
  core/store/hashtree/mem/mod_test.go
  core/store/hashtree/mem/path.go
  core/store/hashtree/mem/path_test.go
  core/store/hashtree/mem/tree.go
  core/store/hashtree/mem/tree_test.go
  core/store/hashtree/mod.go
  core/store/trie/mem/mod.go
  core/store/trie/mem/mod_test.go
  core/store/trie/mem/share.go
  core/store/trie/mod.go
  core/validation/simple/mod_test.go
  internal/mcheck/mod.go
Labels: R4M 🚀
