Repository dedis/dela, pull requests merged in 2020-12, with the labels that each got.

#164 Fixes wrong marshalling of int flags
  cli/node/daemon_test.go
  cli/node/flagset.go
Labels: bug

#165 Refactors cli/node to have an independent urfave implementation
  cli/mod.go
  cli/node/builder.go
  cli/node/builder_test.go
  cli/node/flagset_test.go
  cli/node/mod.go
  cli/ucli/mod.go
  cli/ucli/mod_test.go
  crypto/bls/mod.go
Labels: R4M 🚀, UI

#167 Router: Accept node's address
  mino/minogrpc/rpc.go
  mino/minogrpc/rpc_test.go
  mino/minogrpc/server.go
  mino/router/mod.go
  mino/router/tree/example_test.go
  mino/router/tree/mod.go
  mino/router/tree/mod_test.go
Labels: R4M 🚀
